In [7]:
list_of_items = [23, 45, 4]
list_of_items_2 = [23, 45, 4]
list_of_items * list_of_items_2

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
type(list_of_items)

list

In [8]:
import numpy as np

In [9]:
items = np.array([23, 45, 4])
items_2 = np.array([23, 45, 4])

In [10]:
items

array([23, 45,  4])

In [11]:
items_2

array([23, 45,  4])

In [15]:
type(items)

numpy.ndarray

In [16]:
items * items_2

array([ 529, 2025,   16])

In [17]:
#knowing the size of a numpy array

items.size

3

In [18]:
#knowing the shape of a numpy array (rows, columns)
items.shape

(3,)

In [19]:
items_3 = np.array([[23, 45, 4], [23, 45, 4]])


In [20]:
item_3.shape

NameError: name 'item_3' is not defined

In [21]:
items_3.shape

(2, 3)

In [22]:
items_3.ndim


2

In [25]:
items_4 = np.array([[[23, 45, 4], [23, 45, 4]],[[23, 45, 4], [23, 45, 4]]])

In [26]:
items_4.ndim

3

In [27]:
print(items_4)

[[[23 45  4]
  [23 45  4]]

 [[23 45  4]
  [23 45  4]]]


In [28]:
#accessing items within ndarrays

#1-dimensional arrays items =np.array([23, 45, 4])

items[0]


23

In [29]:
#accessing items within ndarrays

#2-dimensional arrays items_30 = np.array([[23, 45, 4], [20, 43, 4]])
#accessing 45
items_30 = np.array([[23, 45, 4], [20, 43, 4]])
items_30[0,1]


45

In [30]:
#23 and first 4

In [34]:
items_30[0,0]


23

In [35]:
items_30[0,2]

4

In [36]:
items_30[[0,0],[0,2]]

array([23,  4])

In [37]:
#accessing items within ndarrays

#3-dimensional arrays item_4 = np.array([[[23, 45, 4], [23, 45, 4]],[[3, 5, 4], [23, 5, 4]]])
#accessing 3
item_4 = np.array([[[23, 45, 4], [23, 45, 4]],[[3, 5, 4], [23, 5, 4]]])

In [38]:
item_4([1,0,0])

TypeError: 'numpy.ndarray' object is not callable

In [39]:
item_4[1,0,0]

3

In [40]:
#access second column on all rows 45, 45, 5, 5
item_4[[0,0,1],[0,1,1],[1,0,1],[1,1,1]]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [41]:
item_4[0,0,1]

45

In [42]:
item_4[0,1,1]

45

In [43]:
item_4[1,0,1]

5

In [44]:
item_4[1,1,1]

5

In [45]:
item_4[0:,0:,1]

array([[45, 45],
       [ 5,  5]])

In [46]:
item_4[:,:,1]

array([[45, 45],
       [ 5,  5]])

In [47]:
#changing items within ndarrays

#
#1-dimensional arrays items =np.array([23, 45, 4])
#change 45 to 5
items[1] =5

In [48]:
items

array([23,  5,  4])

In [49]:
#changing items within ndarrays

#3-dimensional arrays item_4 = np.array([[[23, 45, 4], [23, 45, 4]],[[3, 5, 4], [23, 5, 4]]])
#change all items in middle column to 8,9,10,11

item_4[:,:,1] = [[8,9],[10,11]]

In [50]:
item_4

array([[[23,  8,  4],
        [23,  9,  4]],

       [[ 3, 10,  4],
        [23, 11,  4]]])